# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Housemates' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Housemates

  target 'HousematesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HousematesUITests' do
    # Pods for testing
  end
  
  pod 'GoogleAPIClientForREST/Sheets', '~> 1.2.1'
  pod 'GoogleSignIn', '~> 4.1.1'

end
